services:
  postgres:
    container_name: threads-db
    image: postgres:16
    ports:
      - 51213:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: threads101
      POSTGRES_DB: threads

volumes:
  postgres_data:
